### PR TITLE
use github actions

### PR DESCRIPTION
**Pull request by kingaa**
This pull request incorporates github actions for checking, testing coverage, and building binaries under various platforms.  These things can be tweaked more, but they seem to be a good start on a continuous-integration strategy that may streamline our code development.

### CODE REVIEW

**Comment by kingaa** [comment]
Pinging to see if this pull request can be acted upon.  Also: I note that Kidus' email address in the DESCRIPTION is out of date.  Since that is used for communication with CRAN, it ought to be kept up to date.

**Comment by ionides** [comment]
I should have some time this week to look into this. In principle, I
suppose it is fairly immediate, but as part of the transition it may be
that I have questions for you. Ed.

Edward L. Ionides
Director of Undergraduate Programs and Professor,
Department of Statistics, University of Michigan
1085 South University, Ann Arbor, MI 48109-1107
email: ***@***.***
phone: 734 615 3332
office: 453 West Hall

**Comment by ionides** [comment]
Aaron, Thanks for the pull request. Mostly, it looks great. There is something I don't understand in README.md

[https://github.com/kingaa/spatPomp/actions/workflows/r-cmd-check.yml/badge.svg](https://github.com/kingaa/spatPomp/actions/workflows/r-cmd-check.yml)

Should we edit kingaa here to kidusasfaw? Perhaps you were doing this edit on your fork? Or is it something specifically set up on your github site? If the latter, I suppose we should set that up on kidusasfaw.

**Comment by kidusasfaw** [comment]
Thanks for merging this change, Ed. And my apologies for forgetting about this, Aaron. Great to see these CI pieces in place.

Kidus

**Comment by kingaa** [comment]
@ionides: Sorry I missed your comment.  Yes, you did right to switch the badges.

**Pull request merged**
